### ISSUE TITLE
Gathering hostnames via Docker

### ISSUE THREAD

**Issue by audrummer15** [18F/domain-scan#106]
As it currently stands, I don't think there is a way to use the gather tool from within the Docker images built from this repo? I think it's worth creating a dockerfile for building an image used to gather hostnames before scanning. I would love some feedback on this idea, and would be more than happy to help out if it is something that is wanted.

**Comment by konklone** [comment]
That would be greatly helpful. I mean, ideally the existing Dockerfile could be modified to do both gathering and scanning, rather than having two separate Dockerfiles. But in any case, Docker-izing the gather entry point is definitely desired.

**Comment by konklone** [comment]
Closing as inactive.
