### ISSUE TITLE
Other scanner types

### ISSUE THREAD

**Issue by adelevie** [18F/domain-scan#13]
@konklone, is this where the other scanners will live, or is `domain-scan` going to remain focused on SSL scanning?

**Comment by konklone** [comment]
@adelevie Check out the `scanners` branch - I did a bunch of refactoring that should make it more clear how to contribute additional scanners.

**Comment by konklone** [comment]
This is where other scanners will live, the plan is very much not for this to be https-focused.

**Comment by gbinal** [comment]
Safe to close this, @adelevie, @konklone ?
