### ISSUE TITLE
No module named 'gatherers.'

### ISSUE THREAD

**Issue by Hwi-Kim** [18F/domain-scan#132]
When i use 
#
sudo ./gather censys,dap, \
		--suffix=.gov \
		--censys_id=id \
		--censys_key=key \
		--dap=https://analytics.usa.gov/data/live/sites-extended.csv \
		--parents=https://raw.githubusercontent.com/GSA/data/gh-pages/dotgov-domains/current-federal.csv 
#
this error was detected

Done fetching from API.
Results written to CSV.
rootk@ubuntu:~/domain-scan-master$ ./st2.sh 
Fetching up to 100 records, starting at page 1.
	[1] Cached page.
[] Gatherer not found, or had an error during loading.
	ERROR: <class 'ImportError'>

	No module named 'gatherers.' 

What is the problem?

**Comment by konklone** [comment]
It looks like you have an extra comma -- it should be `censys,dap`, not `censys,dap,`. We could probably handle that case more gracefully, but if you remove the comma it should work.

**Comment by Hwi-Kim** [comment]
thx! it does worked!
but when i worked this command 
#
./gather censys \
		--suffix=.gov \
		--censys_id=47fdfe67-8d7d-4e54-81eb-2fcdfe89bbf9 \
		--censys_key=UEXqhQ6IAff66sTSZCaEscFUYyGRbl9B \
		--start=1 \
		--end=2 \
		--delay=5 \
		--debug
#
Traceback (most recent call last):
  File "./gather", line 6, in <module>
    import requests

**ImportError: No module named 'requests'**

i am getting this error. What is the problem?
