### ISSUE TITLE
ImportError: No module named 'requests'

### ISSUE THREAD

**Issue by Hwi-Kim** [18F/domain-scan#133]
thx to #132 !!

but  when i worked this command

```
./gather censys 
--suffix=.gov 
--censys_id=id 
--censys_key=key 
--start=1 
--end=2 
--delay=5 
--debug
```

Traceback (most recent call last):
File "./gather", line 6, in 
import requests

**ImportError: No module named 'requests'**

i am getting this error. What is the problem?

i was try to ` pip install requests`

**Comment by konklone** [comment]
Did you follow the instructions in the README and `pip install -r requirements.txt`?

**Comment by Hwi-Kim** [comment]
yes i did.

**Comment by konklone** [comment]
@Hwi-Kim Then I am not sure what to do. It looks like something is amiss in your local environment. I advise starting in a clean environment, and then if you get the error again, copy/paste in the full output of all commands, starting from the first step.

In the meantime, this doesn't appear to be an issue with the tool, so I'm going to close for now. Feel free to post a comment again with the pasted output if the problem reoccurs in a clean environment, and we can look at whether it appears to be an issue with `domain-scan`.

**Comment by Hwi-Kim** [comment]
um... ok..

**Comment by konklone** [comment]
@Hwi-Kim I only mean that I don't have enough information to debug this issue or suggest a next step. If you can reproduce the issue from a clean environment, so that we can see each step involved, I may be in a better position to suggest a next step.
