### ISSUE TITLE
sslyze appearing to stall out on some domains

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#138]
I don't have enough information to report a bug yet. When I checked on our server, the sslyze scans had stalled out with 9 in-flight, with a bunch of `defunct` sslyze processes. These were the domains:

```
nces.ed.gov
autodiscover.ors.od.nih.gov
stg-reg2.hcia.cms.gov
vpn1.cjis.gov
portcullis.nlrb.gov
safesupportivelearning.ed.gov
my.uscis.gov
www.educationusa.state.gov
pittsburgh.feb.gov
```

But when I ran a scan using `sslyze` on all 9 of those in a row, using `--serial`, none of them stalled out. So I'm not totally sure how to reproduce this.

**Comment by konklone** [comment]
cc @h-m-f-t if you've seen anything like this in your own work

**Comment by h-m-f-t** [comment]
```
portcullis.nlrb.gov
my.uscis.gov
```
These two look familiar; I'm pretty certain they threw occasional errors in the early days of pshtt (which probably would have relied on now-defunct capabilities of sslyze). I don't think anything was done client-side to remediate, other than a later re-scan.

**Comment by jsf9k** [comment]
@konklone and @h-m-f-t, I submitted #148 because I was seeing something like this with `pshtt` scans.  When running lots of `pshtt` scans via `domain-scan` I would every once in a while see one or more scans hang indefinitely.  I was able to attach to the hung processes using `gdb` and the debug version of `python`.  The hanging _seems_ to be related to the [public suffix data](https://publicsuffix.org/) being being pulled for every `pshtt` scan being run.  I guess if you pull too often it starts hanging.

I don't know if something similar could be happening inside of `sslyze` runs.  The problem I was seeing would happen with different domains each time, so it was definitely not particular to any given domain.

**Comment by konklone** [comment]
I think I have a decent fix for this in #138. While it doesn't totally identify the root cause, it refactors the tool to use the sslyze library directly, in Python, which cuts down our level of process spawning and indirection. Early signs show that it appears to be making a significant impact on reliability and mitigating zombie processes.

**Comment by jsf9k** [comment]
@konklone, I learned recently that `gdb` can walk python stack traces.  I don't know what OS you're using, but on most linuxes you install the debug version of python, and then run `gdb /path/to/debug/python PID_of_process_to_be_debugged`.  At that point you should be able to run the `py-*` functions like `py-bt` and `py-list` at the `gdb` prompt.

You can read more [here](https://docs.python.org/devguide/gdb.html).  I found that I didn't need to do the `add-auto-load-safe-path` bit at the top of the page.  It seemed to work automagically out of the box once I installed the debug version of python.

I hope that helps some.

**Comment by konklone** [comment]
After trying this with synchronous and concurrent sslyze scanners, and adjusting worker counts, it looks like one of the problems (now and historically) has simply been running out of memory on the machine, and the kernel killing processes.

When I use a synchronous scanner, which runs sslyze in-process, the main domain-scan process/workers are what get killed, which surfaces the error more directly and results in a full cessation of the overall scan. But there are logs in `/var/log/syslog` that show this has been happening for a while, so the kernel was probably killing some of the spawned subprocesses when I was shelling out to `sslyze` (and then when I was using the concurrent scanner, which triggers `sslyze` to do its own multiprocess work) and that was generating zombie processes.

I'm not sure what the next step is here yet, though I may just run sslyze in `--serial` mode (1 worker), which should hopefully keep memory under control (I have a EC2 instance with 8GB of RAM...) for now, at the cost of speed.

**Comment by konklone** [comment]
I'm closing this with the merge of #151, and will re-open if I continue to see this behavior.
