### ISSUE TITLE
Pshtt version

### ISSUE THREAD

**Issue by IanLee1521** [18F/domain-scan#144]
Perhaps this is a Docker-ism that I'm not as familiar with, but is there a reason to pin pshtt to a specific version, rather than leaving the version off and getting the latest from PyPI ? Is this something to optimize the container image building?

https://github.com/18F/domain-scan/blob/8a002b5b1764272ff07bba1a40b3740f7d3ec7fb/Dockerfile#L139

**Comment by konklone** [comment]
I removed this in the latest changes to Dockerfile, it no longer versions pshtt.
