### ISSUE TITLE
Allow mixing of Lambda and non-Lambda scanners

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#163]
Not all scanners are designed for Lambda use, but it's nice to be able to employ them for the ones that do. If a scanner doesn't support Lambda, it'd be great to just assume local scans for that scanner.

Perhaps scanners can opt-in or -out of registering as Lambda-compatible, so that the orchestrator can override the CLI flag for scanners which aren't registered that way.

**Comment by brendansudol** [comment]
close-able now?
