### ISSUE TITLE
Are Node, Go, and PhantomJS needed in Dockerfile?

### ISSUE THREAD

**Issue by jsf9k** [18F/domain-scan#212]
I seem to remember that all the code that used PhantomJS was removed in favor of using headless Chrome.  I'm not sure about the rest.

**Comment by konklone** [comment]
* PhantomJS can go, it uses Chrome now.
* Go can, er, go (that was used for `ssllabs-scan`, which is out).
* Node is still used for Puppeteer/Chrome-based tasks.
* Installing Chrome may be useful for local execution inside of Docker containers. Locally I've been relying on `chrome` being available in the `$PATH`, and the Chrome binary in the repo is so far only used for Lambda execution.

**Comment by jsf9k** [comment]
OK, I'll create a pull request to add Chrome and remove PhantomJS and Go.
