### ISSUE TITLE
Dockerfile needs an update?

### ISSUE THREAD

**Issue by parkr** [18F/domain-scan#25]
Hey! Just checking out this repo and noticed that Dockerfile as-is doesn't build for me:

```text
docker@boot2docker:~/domain-scan$ docker run 5740b16bdfb7
Traceback (most recent call last):
  File "/tmp/scan", line 6, in <module>
    from scanners import utils
  File "/tmp/scanners/utils.py", line 10, in <module>
    import strict_rfc3339
ImportError: No module named 'strict_rfc3339'
```

Running in boot2docker 1.6.2, and `docker version` yields:

```text
docker@boot2docker:~/domain-scan$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Comment by konklone** [comment]
Ah, that's our first Python requirement, and recently added. So it looks like [these two lines](https://github.com/18F/domain-scan/blob/master/Dockerfile#L11-L12) might need to be uncommented:

```
#RUN apt-get update && apt-get install -y python3-pip
#RUN pip3 install -r requirements.txt
```

cc @vzvenyach if he has any guidance on the quickest way to fix it, or if there was a reason it was commented out in the first place.

**Comment by robbi5** [comment]
:+1: for uncommenting the pip lines, this solved the `No module named 'strict_rfc3339'` problem for me too

**Comment by konklone** [comment]
Someone mind doing a quick PR if it works for you? I don't have Docker set up at the moment.

**Comment by parkr** [comment]
@konklone Confirmed in boot2docker on Mac that it works if you uncomment those two lines!

**Comment by parkr** [comment]
Additionally, this needs work related to the output file. So far, I'm not able to see any of the CSV output to the filesystem – only STDOUT gets back to me.

**Comment by parkr** [comment]
> Additionally, this needs work related to the output file. So far, I'm not able to see any of the CSV output to the filesystem – only STDOUT gets back to me.

Looks like I need to add `-v /home/docker/domain-scan:/tmp` to my `run` command (when running on the boot2docker container directly).

**Comment by konklone** [comment]
> Looks like I need to add -v /home/docker/domain-scan:/tmp to my run command (when running on the boot2docker container directly). Correct?

I don't know -- @ozzyjohnson or @vzvenyach might know better. But right now, I'm not using the Dockerfile, and am pretty happy to take PRs to it on faith, if they've been tested locally.
