### ISSUE TITLE
Packaged version of sslyze in lambda/envs/domain-scan.zip is out of date

### ISSUE THREAD

**Issue by buckley-w-david** [18F/domain-scan#251]
In attempting to use a deployed sslyze scanner, the lambda function threw an error when attempting to execute this line:

```
from sslyze.server_connectivity_tester import ServerConnectivityTester, ServerConnectivityError
```

I investigated the `domain-scan.zip` packages, and see that this seems to be the case because the packaged version of sslyze is 1.1.5, whereas according to the requirements file sslyze needs to be version 1.4.1 or greater.

**Comment by jsf9k** [comment]
This issue should be corrected in [dhs-ncats/lambda_functions](https://github.com/dhs-ncats/lambda_functions).  You may prefer to use that project to build your own zip files for AWS Lambda.

**Comment by buckley-w-david** [comment]
Thank you for the tip.

Do you think that information should be added the docs?

**Comment by jsf9k** [comment]
I'd say yes, particularly if `domain-scan.zip` isn't being updated.  It should probably be mentioned in the main `README.md` as well as in `docs/lambda.md`.

You're also welcome to flesh out the documentation of [dhs-ncats/lambda_functions](https://github.com/dhs-ncats/lambda_functions) itself, if you think it's lacking.

**Comment by buckley-w-david** [comment]
Closing due to #252
