### ISSUE TITLE
Report on any errors found during the process

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#29]
At the end of the scan, `--debug` or not, list any errors that gave an `invalid: true` response in their cached data. Possibly include it in the `meta.json` file for the scan, too. It should be easy to find these and re-scan them.

**Comment by gbinal** [comment]
@konklone - Just to confirm, is this still outstanding?  If so, do you want to keep it open?

**Comment by konklone** [comment]
Closing as moot after the refactor in #155.
