### ISSUE TITLE
Only consider a domain preloaded if its preload policy includes subdomains

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#35]
When it comes to HSTS preloading, we're measuring the qualities of the _domain_, not the site at the root of the domain. So, if a domain appears in the list but doesn't include subdomains, for the purpose of our measurement, it should be considered not preloaded.

**Comment by gbinal** [comment]
@konklone - Just to confirm, is this still outstanding?  If so, do you want to keep it open?

**Comment by konklone** [comment]
This is resolved by our switch to [`pshtt`](https://github.com/dhs-ncats/pshtt), which made this logic change internally.
