### ISSUE TITLE
Download the input domain list from a URL

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#37]
As in #36, update the scanner to take a URL as the primary input CSV, not just a local file.

**Comment by gbinal** [comment]
@konklone - By chance, is this now in place, as the scans point tohttps://github.com/18F/pulse/blob/master/meta.yml ?

**Comment by konklone** [comment]
Yes, this is done: https://github.com/18F/domain-scan/blob/d685868b2c85703073dd4348a8f7ef59ced7a372/scan#L46
