### ISSUE TITLE
Update sslyze scanner to use 0.12

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#45]
`--xml_out` can now print to STDOUT, which means we can clean up the file management code in the `sslyze` scanner.

https://github.com/nabla-c0d3/sslyze/releases

**Comment by gbinal** [comment]
@konklone - Just to confirm, is this still outstanding? If so, do you want to keep it open?

**Comment by konklone** [comment]
This is obviated by #151, and long fixed.
