### ISSUE TITLE
Better explanation for https://github.com/18F/domain-scan#setting-tool-paths 

### ISSUE THREAD

**Issue by onceuponatimeforever** [18F/domain-scan#49]
The current instructions aren't clear about where/how to set the environmental variables required for localdev.

**Comment by konklone** [comment]
No? I generally feel like environment variables are so standard in Unix environments that I'm comfortable letting people set that in whatever way works for them.

I use [`autoenv`](https://github.com/kennethreitz/autoenv), would adding a mention of that improve the documentation?

**Comment by onceuponatimeforever** [comment]
It's better to be explicit with the installation instructions than assume that new contributors know how to do a thing. 

I'm :+1: to mentioning `autoenv`.

**Comment by konklone** [comment]
@onceuponatimeforever does #50 help?
