### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by garrettr** [18F/domain-scan#53]
```
$ docker --version
Docker version 1.9.1, build a34a1d5
$ docker-compose up                                    
Building scan
Step 1 : FROM ubuntu:14.04.3
 ---> 6cc0fc2a5ee3
Step 2 : MAINTAINER V. David Zvenyach <vladlen.zvenyach@gsa.gov>
 ---> Using cache
 ---> 9c7124f58945
Step 3 : RUN apt-get update         -qq     && apt-get install         -qq         --yes         --no-install-recommends         --no-install-suggests       build-essential=11.6ubuntu6       curl=7.35.0-1ubuntu2.5       git=1:1.9.1-1ubuntu0.1       libc6-dev=2.19-0ubuntu6.6       libfontconfig1=2.11.0-0ubuntu4.1       libreadline-dev=6.3-4ubuntu2       libssl-dev=1.0.1f-1ubuntu2.15       libssl-doc=1.0.1f-1ubuntu2.15       libxml2-dev=2.9.1+dfsg1-3ubuntu4.4       libxslt1-dev=1.1.28-2build1       libyaml-dev=0.1.4-3ubuntu3.1       make=3.81-8.2ubuntu3       nodejs=0.10.25~dfsg2-2ubuntu1       npm=1.3.10~dfsg-1       python3-dev=3.4.0-0ubuntu2       python3-pip=1.5.4-1ubuntu3       unzip=6.0-9ubuntu1.3       wget=1.15-1ubuntu1.14.04.1       zlib1g-dev=1:1.2.8.dfsg-1ubuntu1       autoconf=2.69-6       automake=1:1.14.1-2ubuntu1       bison=2:3.0.2.dfsg-2       gawk=1:4.0.1+dfsg-2.1ubuntu2       libffi-dev=3.1~rc1+r3.0.13-12       libgdbm-dev=1.8.3-12build1       libncurses5-dev=5.9+20140118-1ubuntu1       libsqlite3-dev=3.8.2-1ubuntu2.1       libtool=2.4.2-1.7ubuntu1       pkg-config=0.26-1ubuntu4       sqlite3=3.8.2-1ubuntu2.1     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Running in eb3383000cf7
E: Version '7.35.0-1ubuntu2.5' for 'curl' was not found
E: Version '1:1.9.1-1ubuntu0.1' for 'git' was not found
E: Version '1.0.1f-1ubuntu2.15' for 'libssl-dev' was not found
E: Version '1.0.1f-1ubuntu2.15' for 'libssl-doc' was not found
E: Version '2.9.1+dfsg1-3ubuntu4.4' for 'libxml2-dev' was not found
E: Version '6.0-9ubuntu1.3' for 'unzip' was not found
ERROR: Service 'scan' failed to build: The command '/bin/sh -c apt-get update         -qq     && apt-get install         -qq         --yes         --no-install-recommends         --no-install-suggests       build-essential=11.6ubuntu6       curl=7.35.0-1ubuntu2.5       git=1:1.9.1-1ubuntu0.1       libc6-dev=2.19-0ubuntu6.6       libfontconfig1=2.11.0-0ubuntu4.1       libreadline-dev=6.3-4ubuntu2       libssl-dev=1.0.1f-1ubuntu2.15       libssl-doc=1.0.1f-1ubuntu2.15       libxml2-dev=2.9.1+dfsg1-3ubuntu4.4       libxslt1-dev=1.1.28-2build1       libyaml-dev=0.1.4-3ubuntu3.1       make=3.81-8.2ubuntu3       nodejs=0.10.25~dfsg2-2ubuntu1       npm=1.3.10~dfsg-1       python3-dev=3.4.0-0ubuntu2       python3-pip=1.5.4-1ubuntu3       unzip=6.0-9ubuntu1.3       wget=1.15-1ubuntu1.14.04.1       zlib1g-dev=1:1.2.8.dfsg-1ubuntu1       autoconf=2.69-6       automake=1:1.14.1-2ubuntu1       bison=2:3.0.2.dfsg-2       gawk=1:4.0.1+dfsg-2.1ubuntu2       libffi-dev=3.1~rc1+r3.0.13-12       libgdbm-dev=1.8.3-12build1       libncurses5-dev=5.9+20140118-1ubuntu1       libsqlite3-dev=3.8.2-1ubuntu2.1       libtool=2.4.2-1.7ubuntu1       pkg-config=0.26-1ubuntu4       sqlite3=3.8.2-1ubuntu2.1     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by vzvenyach** [comment]
@garrettr It's been a while since I've used this, but I've actually been meaning to and have a current use case. Will try and get it going this week.

**Comment by konklone** [comment]
It looks like the `Dockerfile` has [hardcoded versions](https://github.com/18F/domain-scan/blob/master/Dockerfile#L20-L51) that have fallen out of the upstream repos. I'm not experienced enough with Docker to know what best practice is here -- perhaps some form of semantic versioning, or just leaving out the version entirely.

Deferring to @vzvenyach! But @vzvenyach, please let me know if I can be of help here.

**Comment by vzvenyach** [comment]
Looks like @ozzyjohnson added the versioning. Ozzy, is this a best practice?

**Comment by ozzyjohnson** [comment]
@vzvenyach - In my opinion, absolutely. Though, I don't know if you'll find total consensus. For what it's worth, pinning gets [mention in the official best practice docs](https://docs.docker.com/engine/articles/dockerfile_best-practices/).

I think this kind of break is actually a good demonstration of why it's good practice...

1. You know exactly which packages did work.
2. You know which 6 of your 29 packages to look at. 
3. You can easily strip or relax the pin to start troubleshooting.

Contrast that with a newly broken build that lacks pinning...

1. Unless you have CI setup you probably have no idea what combination originally worked.
2. You don't know when or why it broke.
3. You might not have any clear idea where to start looking for the package which silently broke your build.

Ideally, I think you'd have some sort of CI running (Docker Hub automated build if nothing else. I might have set that up to in the 18fgsa org, I don't recall.) and use git branches / tags + docker tags  to ensure there's always a good built image available. At the same time, checking the build status and re-pinning on the dev (or whichever is leading edge) branch becomes part of good housekeeping and maintenance.

**Comment by garrettr** [comment]
In the meantime, would it be helpful for me to file a PR that updates the pinned versions for the affected packages to the latest versions in Ubuntu 14.04.3?

**Comment by ozzyjohnson** [comment]
Sounds good.

**Comment by byeskille** [comment]
I'm not a experienced user in any way, but it seems this problem has arisen again as when I try to use the described method of `docker-compose up` it gives these errors:
`E: Version '1:1.9.1-1ubuntu0.2' for 'git' was not found`
`E: Version '1.0.1f-1ubuntu2.17' for 'libssl-dev' was not found`
`E: Version '1.0.1f-1ubuntu2.17' for 'libssl-doc' was not found`
When checking the system have git version 1:1.9.1-1ubuntu0.3 etc.

Should I myself edit the Dockerfile?

**Comment by ozzyjohnson** [comment]
@byeskille - That would be the fastest way to get going. Just remove the version strings for those packages. `git=1:1.9.1-1ubuntu0.2` would become `git`.

**Comment by byeskille** [comment]
Thanks @ozzyjohnson ! Got it running that way, but still a bit confused where the results data end up as mentioned in #61
