### ISSUE TITLE
Docker builds failing

### ISSUE THREAD

**Issue by afeld** [18F/domain-scan#59]
Have gotten a handful of these notifications:

> There seems to have been an issue with your Automated Build "18fgsa/domain-scan" (VCS repository: 18F/domain-scan) during the build step. You can find more information on
>
> https://hub.docker.com/r/18fgsa/domain-scan/builds/bjafkmaqrftff5tgaytnwgb/

**Comment by konklone** [comment]
Thanks for posting this. I think the answer is that as the primary user of this tool, I need to start using the Docker approach to run it, or else it's going to keep drifting. (If there are other primary users out there, I encourage this as well!)

**Comment by byeskille** [comment]
I'm not at experienced user in any way, but it seems this problem has arisen again as when I try to use the described method of `docker-compose up` it gives these errors:
`E: Version '1:1.9.1-1ubuntu0.2' for 'git' was not found
E: Version '1.0.1f-1ubuntu2.17' for 'libssl-dev' was not found
E: Version '1.0.1f-1ubuntu2.17' for 'libssl-doc' was not found`
When checking the system have git version 1:1.9.1-1ubuntu0.3 etc.
