### ISSUE TITLE
Add docs for getting the results from the docker image

### ISSUE THREAD

**Issue by blkperl** [18F/domain-scan#61]
The README doesn't explain how to get the results from running `docker-compose run scan`. Are they downloaded locally or do they have to be fetched from the docker image some how?

**Comment by konklone** [comment]
This is a good point -- @vzvenyach, I just gave this a go and had the same issue. What's the optimal process here?

**Comment by vzvenyach** [comment]
It's been a while since I've used it, but I'll give it a go today and add documentation.

**Comment by konklone** [comment]
Closing as inactive.
