### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by adelevie** [18F/domain-scan#65]
I know we're all busy, but I figured it's at least worth starting the discussion around this repo's lack of tests. Right now, the only a Python linter (?) is run.

I'll take a first stab at what I think should be tested:
- each scanner with unit tests
- the `./scan` command with unit tests (throw all different args at it, see if it still works)
- an integration test for a big scan

**Comment by adelevie** [comment]
This might make testing quite simple: 

https://docs.travis-ci.com/user/docker/

**Comment by konklone** [comment]
Ideally, `./scan` commands in a test environment would stub out their network functions and get back dummy data -- although that's really the job of each underlying tool where there is one (like `site-inspector`), so maybe we should stub out the shelling-out calls? Though of course it's nice to test the shelling-out too. Maybe a stubbed version of the tests for Travis, and a non-stubbed "environment sanity check" test suite for human use?

**Comment by dogweather** [comment]
I can imagine use a web mock library, and then testing each scanner to verify that it returns the expected results, and in the expected format.

**Comment by konklone** [comment]
Closing as inactive.
