### ISSUE TITLE
Suggestion: Split up the Dockerfile

### ISSUE THREAD

**Issue by afeld** [18F/domain-scan#66]
Just took a look at the Dockerfile for the first time, and was surprised to see how much is in there. I guess it's because the various tools being used all have different dependencies?

Having multiple languages in a single Dockerfile is an antipattern (IMHO), and I think the setup for each scanner could be a lot simpler if you isolated each tool to its own Dockerfile. These could then be run independently, or via a `domain-scan` Dockerfile that calls out to `docker run <scanner>` and then stitches the results together.

I got this idea from the architecture of [the Code Climate CLI](https://github.com/codeclimate/codeclimate), so you could look there for inspiration if you're interested in pursuing this.

**Comment by afeld** [comment]
Also, reached out to see if the architecture motivation/overview/instructions are written down somewhere:

https://twitter.com/aidanfeldman/status/738376676619505664

**Comment by konklone** [comment]
> Having multiple languages in a single Dockerfile is an antipattern (IMHO), and I think the setup for each scanner could be a lot simpler if you isolated each tool to its own Dockerfile. 

@afeld I agree so very wholeheartedly.

cc @garrettr as well

**Comment by afeld** [comment]
We talked about this suggestion at length [in Slack](https://18f.slack.com/archives/docker/p1464877888000035), but just wanted to give a picture of what the Dockerfiles might look like, to hopefully better demonstrate the idea/benefits:

```dockerfile
# Dockerfile-domain-scan
FROM python:3
CMD glue-code-that-calls-docker-run-on-the-others.py

# Dockerfile-sslyze
FROM python:2
RUN wget ...
CMD sslyze

# Dockerfile-inspect
FROM ruby
RUN bundle install
CMD inspect

...
```

**Comment by afeld** [comment]
Hacked on this a bit tonight: https://github.com/18F/domain-scan/pull/67

**Comment by konklone** [comment]
Closing as inactive.
