### ISSUE TITLE
sslyze error where (apparently) no certificates are delivered

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#70]
Observing this sslyze error during scans:

```
Traceback (most recent call last):

  File "/opt/scan/domain-scan/scan", line 120, in process_scan
    rows = list(scanner.scan(domain, options))

  File "/opt/scan/domain-scan/scanners/sslyze.py", line 75, in scan
    data = parse_sslyze(xml)

  File "/opt/scan/domain-scan/scanners/sslyze.py", line 205, in parse_sslyze
    issuer = certificates[-1].select_one("issuer commonName")

IndexError: list index out of range
```

These appear to happen after a long timeout, suggesting that there could be a connection/timeout error that results in no certificate data being available.

**Comment by gbinal** [comment]
@konklone - Just to confirm, is this still outstanding? If so, do you want to keep it open?

**Comment by konklone** [comment]
Closing unless I see it reoccur, since we've so heavily refactored the sslyze integration.
