### ISSUE TITLE
Nothing is return for a specific domain name

### ISSUE THREAD

**Issue by ThibautGery** [18F/domain-scan#73]
```bash
$ docker-compose run scan particulier.api.gouv.fr --scan=tls
Results written to CSV.
```
But the file `results/tls.csv` is empty
```sh
$ cat results/tls.csv 
Domain,Base Domain,Grade,Signature Algorithm,Key Type,Key Size,Forward Secrecy,OCSP Stapling,Fallback SCSV,RC4,SSLv3,TLSv1.2,SPDY,Requires SNI,HTTP/2
```
But i works well in the [interface](https://www.ssllabs.com/ssltest/analyze.html?d=particulier.api.gouv.fr&latest)

This command `docker-compose run scan geo.api.gouv.fr --scan=tls` works.

Nothing is printed on `stderr`. Do you know where is the problem ?

**Comment by konklone** [comment]
Can you try running it with the `--debug` flag to see if that spits anything out?

I get this when I run the command (directly, not through `docker-compose`):

```
2016/07/29 15:28:20 [DEBUG] Response #6 status: HTTP/1.1 200 OK
2016/07/29 15:28:20 [DEBUG] Server set current assessments to 0
2016/07/29 15:28:20 [DEBUG] Server set maximum assessments to 24
2016/07/29 15:28:21 [INFO] Assessment complete: particulier.api.gouv.fr (1 host in 15 seconds)
    188.165.32.249: Err: Unable to connect to the server
2016/07/29 15:28:21 [DEBUG] Active assessments: 0 (more: false)
2016/07/29 15:28:21 [INFO] All assessments complete; shutting down
Results written to CSV.
```

Note the `188.165.32.249: Err: Unable to connect to the server` line. I believe that's from the SSL Labs API, talking about the domain you're testing it against.

Also, when I [visit the SSL Labs interface](https://www.ssllabs.com/ssltest/analyze.html?d=particulier.api.gouv.fr), it doesn't work for me:

<img width="860" alt="screen shot 2016-07-29 at 1 49 08 pm" src="https://cloud.githubusercontent.com/assets/4592/17261497/47366998-5593-11e6-8b98-42f06b94f616.png">

So I think there is an issue with the server of some sort, but I'm not sure what error that is. When I try to connect with `curl` and `openssl s_client`, I can connect just fine.
