### ISSUE TITLE
Convert a11y, tls, other scanners to use pshtt data instead

### ISSUE THREAD

**Issue by konklone** [18F/domain-scan#79]
They currently use the `inspect` scanner (to determine the "canonical" URL), let's have them use `pshtt` instead.

**Comment by gbinal** [comment]
I believe that a11y is the last of these that needs to migrate to `pshtt`.  https://github.com/18F/domain-scan/issues/91 should then serve for this issue going forward.  

I'm going to go ahead and close this though feel free to reopen if I'm mistaken.
