### ISSUE TITLE
Change the way `try_command()` checks command

### ISSUE THREAD

**Issue by siccovansas** [18F/domain-scan#96]
I'm trying to call `pshtt` as a docker container, which results in something like the following command being passed executed by `domain-scan`:

```
docker run --rm -e USER_ID=1042 -e GROUP_ID=1042 -v $(pwd):/data dockerpulse_c-pshtt rijksoverheid.nl
```

This fails when a scanner tries this command using `try_command()`[[code](https://github.com/18F/domain-scan/blob/master/scanners/utils.py#L135)], because it runs `which` on the whole command including parameters. This could be 'fixed' if only the actual executable of the command is passed to `which`, e.g.:

```
subprocess.check_call(["which", command.split(' ')[0]], ...)
```

I'm not sure if this has any implications, so I made an issue out of this instead of a pull request.

**Comment by konklone** [comment]
I'm closing this as moot, since the `pshtt` scanner now uses the `pshtt` Python API and doesn't shell out anymore. Please feel free to re-open or open a new issue if you still have issues along these lines.
