### ISSUE TITLE
a11y.py scan is not ignoring individual errors 

### ISSUE THREAD

**Issue by gbinal** [18F/domain-scan#99]
In step 5 of the a11y [scanning process](https://github.com/18F/domain-scan/wiki/a11y-scanning-process), the [a11y.py](https://github.com/18F/domain-scan/blob/make-lambda-optional/scanners/a11y.py) scan is not excluding individual errors that are listed in the [ignore list](https://github.com/18F/domain-scan/blob/make-lambda-optional/scanners/a11y.py#L54-L91).  Right now, to get by, I go back in and hand remove them from the a11y.csv file that is generated after step 5, but this is laborious and error prone.   

Notices and warnings are correctly excluded but not the individual errors.  It's as if I hadn't included them there.  

I suspect that this comes from them being improperly formatted or referenced, though I don't know how.  Here's some documentation that I've found: 
* https://github.com/pa11y/pa11y#ignoring
* https://github.com/pa11y/pa11y#ignore-array

**Comment by gbinal** [comment]
Here's a good test of this:  

Right now, here are some of the errors I'm seeing in results that I think I shouldn't be seeing.  

`WCAG2AA.Principle1.Guideline1_3.1_3_1.H63` is returning 163 errors, but just on one site:  economicinclusion.gov.  

The following sites are each returning 1 error of `WCAG2AA.Principle2.Guideline2_4.2_4_2.H25.1.NoTitleEl`.  

* bia.gov
* ciso.gov
* cyber.gov
* cybersecurity.gov
* e-enterprise.gov
* ecopartnerships.gov
* indianaffairs.gov
* ipp.gov
* lca.gov
* nolaenvironmental.gov
* stb.gov
* usda.gov

**Comment by micahsaul** [comment]
Looks like a formatting error in pa11y_config.json.

**Comment by gbinal** [comment]
Yep.  That was it.  THANK YOU!

**Comment by gbinal** [comment]
I'm attempting to correct these issues with https://github.com/18F/domain-scan/commit/f4ee1d47345ceb07a4ef5ed20a2b56105cb1bad8

**Comment by gbinal** [comment]
Note that I needed to further refine the ignore list by adding:  

```
WCAG2AA.Principle1.Guideline1_3.1_3_1.H42.2
WCAG2AA.Principle1.Guideline1_3.1_3_1.H43.HeadersRequired
WCAG2AA.Principle1.Guideline1_3.1_3_1.H63.1
WCAG2AA.Principle1.Guideline1_3.1_3_1.H71.NoLegend
WCAG2AA.Principle1.Guideline1_3.1_3_1.H73.3.LayoutTable
WCAG2AA.Principle3.Guideline3_1.3_1_1.H57.3.Lang
WCAG2AA.Principle3.Guideline3_1.3_1_1.H57.3.XmlLang
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Button.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Fieldset.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputButton.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputCheckbox.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputImage.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputPassword.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputRadio.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.InputText.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Select.Name
WCAG2AA.Principle4.Guideline4_1.4_1_2.H91.Textarea.Name
```

**Comment by gbinal** [comment]
Doing so here - https://github.com/18F/domain-scan/pull/119
